name: Python Linting and Formatting

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint black

            - name: Lint with pylint
              run: |
                  pylint JSONManipulator/
              env:
                  PYLINTHOME: ${{github.workspace}}
              continue-on-error: true

            - name: Format with black
              run: black JSONManipulator/

    # Add more jobs for building and testing your application if needed
