name: Python Syntax Check

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pylint black

      - name: List modified files
        id: list_files
        run: echo "::set-output name=files::$(git diff --name-only HEAD $(git merge-base HEAD master) | grep '\.py$' || true)"

      - name: Run Pylint
        run: pylint --output-format=parseable ${{ steps.list_files.outputs.files }}

      - name: Run Black
        run: black --check --diff ${{ steps.list_files.outputs.files }}
