name: Python Linting and Formatting

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out code
              uses: actions/checkout@v2

            - name: Set up of Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint black

            - name: Running PyLint
              run: |
                  pylint JSONManipulator/
              env:
                  PYLINTHOME: ${{github.workspace}}
              continue-on-error: true
