name: Python Linting and Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black

      - name: Lint with pylint
        run: |
          pylint src/
          pylint tests/ --disable=missing-docstring
        env:
          PYLINTHOME: ${{github.workspace}}

      - name: Format with black
        run: black src/ tests/

  # Add more jobs for building and testing your application if needed
