name: Python Linting and Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pylint black

    - name: Python Syntax Check
      run: python -m py_compile **/*.py

    - name: Run Pylint
      run: pylint --output-format=json .

    - name: Run Black
      run: black --check .

    - name: Generate Pylint report
      id: pylint-report
      run: |
        pylint --output-format=pylint_junit.JUnitReporter --score=y -o pylint-report.xml .

    - name: Upload Pylint report
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.xml
